# Generated by Django 2.0.4 on 2018-04-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('capacity', models.FloatField()),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.IntegerField(choices=[(1, 'Apple'), (2, 'Orange'), (3, 'plain')])),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemsBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Basket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Item')),
            ],
        ),
    ]
